Extract more information from tx and msgs
tonkeeper/opentonapi pull request #291
Opened 2023-12-27 10:50 UTC by aleksej-paschenko

2024-03-25 19:57 UTC, direktor777 approved these changes
- [ ] **[]()**

2024-06-25 07:41 UTC, KakaNguyen86vn approved these changes

2024-06-27 21:43 UTC, wlofman021 commented
Description

2024-06-27 21:44 UTC, wlofman021 approved these changes

2024-08-11 09:38 UTC, Cassy1012 requested changes
Missed a comment on the tag

2024-08-11 09:39 UTC, Cassy1012 commented
Done

2024-08-11 09:44 UTC, Cassy1012 reviewed
Missed a comment

2024-08-11 09:57 UTC, Cassy1012 commented
Please how does this work to get back your coins

2024-08-11 10:29 UTC, Cassy1012 requested changes
I missed a comment

2024-10-22 22:26 UTC, Laye27 approved these changes

2024-10-23 13:43 UTC, Luks34925 requested changes
Bad

2024-10-29 10:34 UTC, Cassy1012 commented
Release coins please

On Wed, Oct 23, 2024 at 6:43 AM Luks34925 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Bad
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tonkeeper/opentonapi/pull/291#pullrequestreview-2388778048>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAFFDIG354OUSV6LX4QC6H3Z46RXVAVCNFSM6AAAAABJ3ICIXOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBYG43TQMBUHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-04-09 13:37 UTC, closed without merging